//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person_WithMoreInfo
    {
        public int Person_Id { get; set; }
        public string Name { get; set; }
        public int Company_Id { get; set; }
        public string Filter_Property_1 { get; set; }
        public Nullable<double> Filter_Property_2 { get; set; }
        public string Addtional_Property_1 { get; set; }
        public string Addtional_Property_2 { get; set; }
        public string Addtional_Property_3 { get; set; }
        public string Addtional_Property_4 { get; set; }
        public string Addtional_Property_5 { get; set; }
        public string Addtional_Property_6 { get; set; }
        public string Addtional_Property_7 { get; set; }
        public string Addtional_Property_8 { get; set; }
        public string Addtional_Property_9 { get; set; }
        public string Addtional_Property_10 { get; set; }
        public string Addtional_Property_11 { get; set; }
        public string Addtional_Property_12 { get; set; }
        public string Addtional_Property_13 { get; set; }
        public string Addtional_Property_14 { get; set; }
        public string Addtional_Property_15 { get; set; }
        public string Addtional_Property_16 { get; set; }
        public string Addtional_Property_17 { get; set; }
        public string Addtional_Property_18 { get; set; }
        public string Addtional_Property_19 { get; set; }
        public string Addtional_Property_20 { get; set; }
        public string Addtional_Property_21 { get; set; }
        public string Addtional_Property_22 { get; set; }
        public string Addtional_Property_23 { get; set; }
        public string Addtional_Property_24 { get; set; }
        public string Addtional_Property_25 { get; set; }
        public string Addtional_Property_26 { get; set; }
        public string Addtional_Property_27 { get; set; }
        public string Addtional_Property_28 { get; set; }
        public string Addtional_Property_29 { get; set; }
        public string Addtional_Property_30 { get; set; }
        public string Addtional_Property_31 { get; set; }
        public Nullable<int> Addtional_Property_32 { get; set; }
        public Nullable<int> Addtional_Property_33 { get; set; }
        public Nullable<int> Addtional_Property_34 { get; set; }
        public Nullable<int> Addtional_Property_35 { get; set; }
        public Nullable<System.DateTime> Addtional_Property_36 { get; set; }
        public Nullable<int> Addtional_Property_37 { get; set; }
        public Nullable<int> Addtional_Property_38 { get; set; }
        public Nullable<double> Addtional_Property_39 { get; set; }
        public Nullable<int> Addtional_Property_40 { get; set; }
        public string Addtional_Property_41 { get; set; }
        public string Addtional_Property_42 { get; set; }
        public string Addtional_Property_43 { get; set; }
        public Nullable<int> Addtional_Property_44 { get; set; }
        public string Addtional_Property_45 { get; set; }
        public Nullable<int> Addtional_Property_46 { get; set; }
        public System.Guid Addtional_Property_47 { get; set; }
        public Nullable<bool> Addtional_Property_48 { get; set; }
        public Nullable<bool> Addtional_Property_49 { get; set; }
        public string Addtional_Property_50 { get; set; }
        public Nullable<double> Addtional_Property_51 { get; set; }
        public Nullable<bool> Addtional_Property_52 { get; set; }
        public string Addtional_Property_53 { get; set; }
        public string Addtional_Property_54 { get; set; }
        public Nullable<int> Addtional_Property_55 { get; set; }
        public Nullable<int> Addtional_Property_56 { get; set; }
        public Nullable<decimal> Addtional_Property_57 { get; set; }
        public Nullable<decimal> Addtional_Property_58 { get; set; }
        public string Addtional_Property_59 { get; set; }
        public bool Addtional_Property_60 { get; set; }
        public Nullable<bool> Addtional_Property_61 { get; set; }
        public Nullable<int> Addtional_Property_62 { get; set; }
        public Nullable<int> Addtional_Property_63 { get; set; }
        public Nullable<int> Addtional_Property_64 { get; set; }
        public Nullable<int> Addtional_Property_65 { get; set; }
        public bool Addtional_Property_66 { get; set; }
        public Nullable<int> Addtional_Property_67 { get; set; }
        public Nullable<int> Addtional_Property_68 { get; set; }
        public Nullable<int> Addtional_Property_69 { get; set; }
        public Nullable<int> Addtional_Property_70 { get; set; }
        public Nullable<System.Guid> Addtional_Property_71 { get; set; }
        public Nullable<int> Addtional_Property_72 { get; set; }
        public Nullable<int> Addtional_Property_73 { get; set; }
        public Nullable<int> Addtional_Property_74 { get; set; }
        public Nullable<int> Addtional_Property_75 { get; set; }
        public Nullable<System.DateTime> Addtional_Property_76 { get; set; }
        public Nullable<int> Addtional_Property_77 { get; set; }
        public string Addtional_Property_78 { get; set; }
        public Nullable<System.DateTime> Addtional_Property_79 { get; set; }
        public Nullable<int> Addtional_Property_80 { get; set; }
        public string Addtional_Property_81 { get; set; }
        public bool Addtional_Property_82 { get; set; }
        public Nullable<int> Addtional_Property_83 { get; set; }
        public Nullable<System.DateTime> Addtional_Property_84 { get; set; }
        public Nullable<int> Addtional_Property_85 { get; set; }
        public Nullable<int> Addtional_Property_86 { get; set; }
        public Nullable<int> Addtional_Property_87 { get; set; }
        public Nullable<System.Guid> Unique_Id { get; set; }
    }
}
