//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SimplifiedModelEntities : DbContext
    {
        public SimplifiedModelEntities()
            : base("name=SimplifiedModelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<Person_WithMoreInfo> Person_WithMoreInfo { get; set; }
    
        [DbFunction("SimplifiedModelEntities", "Person_GetForCompany")]
        public virtual IQueryable<Person_GetForCompany_Result> Person_GetForCompany(Nullable<int> company_Id)
        {
            var company_IdParameter = company_Id.HasValue ?
                new ObjectParameter("Company_Id", company_Id) :
                new ObjectParameter("Company_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Person_GetForCompany_Result>("[SimplifiedModelEntities].[Person_GetForCompany](@Company_Id)", company_IdParameter);
        }
    }
}
